"""Changes to db

Revision ID: a19eeb680f95
Revises: 6e11a4181e2a
Create Date: 2020-05-09 20:31:01.040044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a19eeb680f95'
down_revision = '6e11a4181e2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('comment_userid_fkey', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['id'])
    op.drop_column('comment', 'userid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('userid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_userid_fkey', 'comment', 'user', ['userid'], ['id'])
    op.drop_column('comment', 'user_id')
    # ### end Alembic commands ###
